services:
  - type: web
    name: face-recognition-system
    env: docker
    plan: free # 使用免费套餐
    region: singapore # 选择新加坡服务器，对亚洲访问更友好
    healthCheckPath: /
    dockerContext: ./camera_projects/face_recognition_system
    dockerfilePath: ./camera_projects/face_recognition_system/Dockerfile 